apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: hometheatre
  sources:
  - chart: plex/plex-media-server
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/base/builds/regulus/argocd/projects/hometheatre/manifests/plex/values.yaml
  - repoURL: ssh://git@github.com/tkjode/homelab
    targetRevision: HEAD
    ref: values
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false