apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/name: shell-pod
    app.kubernetes.io/part-of: hometheatre
  name: hometheatre-pod
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shell-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shell-pod
    spec:
      containers:
      - image: busybox
        name: shell
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources: {}
        volumeMounts:
        - mountPath: /lun1
          name: lun1
      volumes:
      - name: lun1
        persistentVolumeClaim:
          claimName: pvc-dblmounttest-config
