apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-anime
  namespace: plex
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 16Ti
  accessModes:
  - ReadWriteMany  
  nfs:
    path: /srv/nas/media/video/Anime
    server: 10.0.0.5