apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  namespace: plex
spec:
  storageClassName: iscsi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 16Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.64.16:3260
    iqn: iqn.2026-02.com.phalnet.regulus:pv00
    lun: 1
    fsType: ext4
    readOnly: false