apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tvshows
  namespace: plex
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  reclaimPolicy: Retain
  capacity: 16Ti  
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nas/media/video/tvshows
    server: 10.0.0.5