apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  namespace: plex
spec:
  storageClassName: nfs-durable
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.5
    path: /srv/regulus/stateful/plex#config