apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16G
  storageClassName: iscsi
  volumeMode: Filesystem
  volumeName: plex-config