apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dblmounttest-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: iscsi
  volumeMode: Filesystem
  volumeName: dblmounttest-config