apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: iscsi
  volumeMode: Filesystem
  volumeName: plex-config