httpRoute:
  enabled: true
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-ingress
    namespace: default
  hostnames:
  - "plex.apps.phalnet.com"
pms:
  storageClassName: nfs-durable
  configStorage: 8G
extraVolumnes:
- name: plex-tvshows
  persistentVolumeClaim:
    claimName: pvc-plex-tvshows
- name: plex-movies
  persistentVolumeClaim:
    claimName: pvc-plex-movies
- name: plex-anime
  persistentVolumeClaim:
    claimName: pvc-plex-anime