extraEnv:
  HOSTNAME: regulus
  ALLOWED_NETWORKS: "10.0.0.0/8,192.168.64.0/24,172.16.0.0/16"
  ADVERTISE_IP: "https://plex.apps.phalnet.com/"
  TZ: "America/New_York"
  PLEX_CLAIM: claim-a5PoBM4yevQMWBKLRdMs
httpRoute:
  enabled: true
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-ingress
    namespace: default
  hostnames:
  - "plex.apps.phalnet.com"
pms:
  configExistingClaim: pvc-plex-config
extraVolumes:
- name: plex-tvshows
  persistentVolumeClaim:
    claimName: pvc-plex-tvshows
- name: plex-movies
  persistentVolumeClaim:
    claimName: pvc-plex-movies
- name: plex-anime
  persistentVolumeClaim:
    claimName: pvc-plex-anime
extraVolumeMounts:
- name: plex-tvshows
  mountPath: /tvshows
- name: plex-movies
  mountPath: /movies
- name: plex-anime
  mountPath: /anime