apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: htpc-projects
resources:
  - AppProject.hometheatre.yaml                     # Creates the `hometheatre` argocd project
  - manifests/plex/Application-plex.yaml            # Adds the Helm chart to ArgoCD in the hometheatre project
  - manifests/nzbget/Application-nzbget.yaml        # Build starting