apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nzbget
  namespace: argocd
spec:
  project: hometheatre
  sources:
  - repoURL: ssh://git@github.com/tkjode/homelab
    targetRevision: HEAD
    path: base/builds/regulus/argocd/projects/hometheatre/manifests/nzbget
  destination:
    namespace: nzbget
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false