apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nzbget
  namespace: nzbget
spec:
  hostnames:
  - nzbget.apps.phalnet.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-ingress
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: nzbget
      port: 6789
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /