apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nzbget
resources:
  - pv-cachedir.yaml
  - pvc-cachedir.yaml
  - pv-downloads.yaml
  - pvc-downloads.yaml
  - deployment-nzbget.yaml
#  - service-
#  - httproute-