apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  namespace: nzbget
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 256Mi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nas/kubepv/regulus/stateful/nzbget#config
    server: 10.0.0.5
