apiVersion: v1
kind: PersistentVolume
metadata:
  name: cachedir
  namespace: nzbget
spec:
  storageClassName: iscsi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 384Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.64.3:3260
    iqn: iqn.2026-02.com.phalnet.regulus:pv00
    lun: 2
    fsType: ext4
    readOnly: false  