apiVersion: v1
kind: PersistentVolume
metadata:
  name: exports-sonarranime
  namespace: nzbget
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 16Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nas/kubepv/regulus/stateful/sonarranime#exports
    server: 10.0.0.5
