apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exports-sonarranime
  namespace: nzbget
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: exports-sonarranime
