#cloud-config
hostname: bastion
timezone: America/Toronto
write_files:
users:
  - default
  - name: tkjode
    groups:
      - sudo
    shell: /bin/bash
    ssh_import_id: ['gh:tkjode']
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
  - haproxy
  - kustomize
  - iptables-persistent
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - apt update && apt -y install kubectl && apt-mark hold kubectl
  - apt -y dist-upgrade
  - apt -y autoremove
  - snap refresh
  - echo "done" > /tmp/cloud-config.done