apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bios
resources:
  - AppProject.networking.yaml
  - AppProject.trusted-platform.yaml
  - AppProject.storage.yaml
  - AppProject.telemetry.yaml
  - ApplicationSet.bootstrap.yaml