apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-movies
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: plex-movies